### ISSUE TITLE
 Retina Image Feature - Implement ability to view related retina images (Get/Read)

### ISSUE THREAD

**Issue by NeffCodes** [NeffCodes/retinopathy-risk-assessment-tool#21]
Add ability for displaying all related images to an individual patient. 
- Image details should include seeing the position, date created, current status and prognosis.
- Ensure that only retina images added to patient are displayed (aka, Frankie Steins scans are only displayed on her page, not Joe Star's page).
- organize to display most recent first. 
- This includes basic styling of the images and related info on the patients individual page. It does not include creating a way to filter or sort images
- This does not include adding a toggle or button to send off to the wizard. That will be a feature 3 implementation.

**Comment by SNMeans** [comment]
Tasks:
- Set up a GET endpoint in Django views to retrieve retina images from the database.
- Update the patient dashboard template to show these images.
- Test on the front end.

**Aim to complete by Thursday Nov 7**

**Comment by SNMeans** [comment]
**11/07 Update:**
1. Created  ```patient_images``` view in views.py to retrieve all retina photos associated with each patient + made them ordered by the most recent upload.
2) Updated ```view_patient.html``` to include a section that displays the retina photos along with other details like position(OS vs OD), date created, status, and prognosis. A message is shown if 'no retina photos are available.'
3) Tested on front-end; it works! but....The images are quite large.

Next Steps *Complete by Friday 11/08*: I’ll work on making sure the retina photos are all resized to a standard 256x256 pixels, regardless of their original dimensions, so the display remains consistent.
