### ISSUE TITLE
#4 Develop REST API Endpoint and Integration

### ISSUE THREAD

**Issue by SNMeans** [NeffCodes/retinopathy-risk-assessment-tool#46]
Description: Set up an endpoint to allow real-time diagnostic analysis through the frontend, allowing retina scan submission and prediction result displaying on the patient dashboard/patient profile.

Tasks
- Create a REST API endpoint ```(/predict)``` to receive and process image submissions.
- Create ```process_image()``` function to handle image preprocessing and model inference.
- Integrate the diagnostic results display on the frontend/patient dashboard

**Comment by NeffCodes** [comment]
In my mind we can break this down into the following tickets.

1. Ticket A - Create the server. aka the initial backend setup (whether with flask or django again)
2. Ticket B - [dependent on A] Create a new endpoint `/predict`. Have the initial return being `Hello World` to verify endpoint works. 
3. Ticket C - [dependent on B] Build out the business logic for the image processing for the endpoint to return the data needed. 
4. In the other repository, we should verify that we have a ticket to receive said data from the wizard and update our databases

**Comment by NeffCodes** [comment]
Split into smaller tickets, closing out this one. (tickets, 55-59)
